boto/connection.py
https_validate_certificates==False stopped working because of:
https://docs.python.org/2/library/httplib.html#httplib.HTTPSConnection
=> fixed https_validate_certificates==False for python 2.7.9

boto/ec2/blockdevicemapping.py
1. Removed invalid ".Ebs." from the "NoDevice" parameter.
2. If "NoDevice" is needed, will no longer list any "Ebs" type parameters as they were causing AWS to launch instances with no root device at all (even if a 3nd block device was defined).
3. Removed  "true" value from ".NoDevice" parameter.
=> cherry-pick fix commit

Makefile, python-boto.spec
Release builds (with tag): `python-boto-%ver-CROC#.%dist.rpm`
Devel builds (without tag): `python-boto-%ver-CROC#.%Y%m%d%H%M.git%sha.%dist.rpm`
=> makefile: ability to build develop rpm package

boto/ec2/address.py, boto/ec2/connection.py, tests/unit/ec2/test_address.py
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateAddress.html
Signed-off-by: Anton Vazhnetsov <dragen15051@gmail.com>
=> ec2: fix 'AllowReassociation' param according to AWS API

setup.py
=> compat: dont use strict requires to ordereddict

boto/ec2/connection.py
'tags' parameter in 'delete_tags()' is now optional (defaults to None).
=> ec2: Allow Tags deletion by resource ID only

.travis.yml
in latest travis [update](https://changelog.travis-ci.com/xenial-as-the-default-build-environment-99476) default dist was changed to ubuntu 16.10 which lacks python 2.6 and 3.3.
this pr pinned older ubuntu version which supports 2.6 and 3.3 python.
=> travis: pin ubuntu dist

.travis.yml, python-boto.spec
This PR enables python3.x rpm builds by default for RHEL/CentOS 7.5+ dists.
=> specfile: add support for epel py3 builds

.travis.yml, README.rst
remove 3.3 3.4 3.5 python versions from travis test matrix
=> tavis.yml: remove deprecated python versions from test matrix

boto/ec2/connection.py
Add tagging on creation for RunInstances, CreateVolume, CreateSnapshot
**EC2Connection.run_instances**
added arguments 
* instance_tags
* volume_tags
**EC2Connection.create_volume**
added arguments 
* tags
**EC2Connection.create_snapshot**
added arguments 
* tags
=> ec2: add tagging on creation for RunInstances, CreateVolume, CreateSnapshot

boto/ec2/address.py, boto/ec2/address_pool.py, boto/ec2/connection.py, boto/ec2/keypair.py, boto/ec2/placementgroup.py
[DescribePublicIpv4Pools](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribePublicIpv4Pools.html) have filters param but get_all_public_ipv4_pools doesn't have it.
Changes
*EC2Connection.get_all_public_ipv4_pools*
* added _filter_ argument, addition to request params if filters present
*Address* is now based on TaggedEC2Object
*AddressPool* is now based on TaggedEC2Object
*KeyPairs* is now based on TaggedEC2Object, and parses *keyPairId* as .id
*Placement* is now based on TaggedEC2Object, and parses *groupId* as .id
=> ec2: add filters for get_all_public_ipv4_pools

boto/ec2/connection.py
Keypairs are in list of resources that can be tagged during creation. So:
_EC2Connection.create_key_pair_:
- added param tags applied to new key pair
_EC2Connection.import_key_pair_:
- added param tags applied to new key pair
=> ec2: Tagging keypairs on creation and import 

boto/ec2/connection.py, boto/utils.py, boto/vpc/__init__.py
Changes: 
Added option for tagging on creation for:
* ACLs
* DHCP options
* Network interfaces
* Placement groups
* Route tables
* Security groups
* Subnets
* VPCs
=> EC2, VPC: Tagging on creation

.travis.yml
The 'master' became default branch after remove 'devel' branch. 
In this PR we removed validation the master branch in travis for allow testing.
=> travis: remove validation for master branch

boto/ec2/connection.py
Changes: 
*ec2.connection.run_instances* - Remove description argument
Explanation: Description is a tag from now on
=> C2DEVEL-9093: remove description from instances

boto/ec2/connection.py
Add hibernate option support to stop instances command.
The QGA command guest-suspend-to-disk will be sent on this option.
=> ec2: add hibernate option to stop_instances

boto/vpc/vpc.py
__Changes__: 
1. removed `.description` attribute from VPC
=> VPC: remove unused vpc.description attribute

boto/ec2/connection.py
This pr in combination with #128 completely eliminates Instance section of our custom API, so I removed `Instances` commentary too.
Signed-off-by: Pavel Kulyov <pkulev@croc.ru>
=> C2DEVEL-7317: drop legacy Virtual Network API

boto/ecs/item.py, python-boto.spec, tests/db/test_password.py, tests/unit/utils/test_utils.py
Fix spec and tests to build for redos
=> C2DEVEL-14669: Build for redos 7.3c

boto/ec2/connection.py, boto/ec2/instance.py
https://jira.croc.ru/browse/C2DEVEL-15441
=> C2DEVEL-15441: Add RamMonitoring Instance attribute
