boto/vpc/__init__.py, boto/vpc/customergateway.py, boto/vpc/dhcpoptions.py, boto/vpc/subnet.py, boto/vpc/vpc.py, boto/vpc/vpnconnection.py, boto/vpc/vpngateway.py
Backported with changes from `2.9.0` version.
Methods are implemented in `VPCConnection`.
=> Added 'get_vpc_attribute' and 'modify_vpc_attribute' methods

boto/__init__.py
Add "connect_cloudwatch_endpoint" helper. It is similar to "connect_ec2_endpoint".
=> connect_cloudwatch_endpoint

boto/ec2/connection.py, boto/ec2/export_task.py, boto/ec2/import_task.py, tests/unit/ec2/test_importexport.py
=> Import export -> master

boto/ec2/blockdevicemapping.py, boto/ec2/connection.py, boto/ec2/volume.py, python-boto.spec, tests/unit/ec2/test_volume.py
=> EC2: remove tiers.

boto/vpc/__init__.py, boto/vpc/vpc.py
Signed-off-by: Evgeniy Solntsev <esolntsev@croc.ru>
=> vpc: remove AZ field from vpcs api

.travis.yml, Makefile, README.rst, python-boto.spec
=> Added RPM spec and Makefile

README.rst
=> Fix travis badges

requirements-docs.txt, requirements.txt
=> Freeze max versions for paramiko and cryptography

boto/exception.py
=> boto: dont decode bytes string in PY2 when parse error message

boto/ec2/connection.py
Next parameters are implemented:
* instance_id
* group_name
=> ec2: Add 'modify-instance-placement' method

python-boto.spec
=> rpm: bump release

boto/ec2/cloudwatch/__init__.py, boto/ec2/cloudwatch/alarm.py
Parameters added:
* datapoints_to_alarm
* treat_missing_data
=> cw: add new parameters to MetricAlarm __init__

requirements.txt
=> travis: fix travis build

python-boto.spec
=> rpm: bump boto version

boto/ec2/connection.py, boto/ec2/tariff.py
A new method get_tariff added. It returns customer's specific tariff
=> ec2: add get_tariff method

python-boto.spec
=> spec: update changelog

.travis.yml
update travis.yaml with rpmlint checker
=> Add rpm spec linter

Makefile
* create help target
* create lint target
* swap GIT ifdef clause with assert-command function
=> Makefile refactoring

boto/cloudtrail/layer1.py
Added aws_sudo_id parameter processing to CloudTrail init method
Added X-Aws-Sudo-Id header to http_request
=> Add aws_sudo_id support to cloudtrail

boto/ec2/connection.py
Add 2 arguments to 'get_all_extnetworks' method:
ext_net_names
filters
=> EC2: Modify 'get_all_extnetworks' method

boto/vpc/__init__.py, boto/vpc/vpnconnection.py, python-boto.spec
https://jira.croc.ru/browse/C2DEVEL-9047
=> C2DEVEL-9047: vpnc tunnel opts spec

boto/ec2/tariff.py
Changes:
* Added deprecation status to TariffInstance, TariffService, TariffVolume
=> tariff: add deprecation status to instance type, volume type, other

boto/ec2/connection.py, boto/ec2/networkinterface.py
Signed-off-by: Pavel Kulyov <kulyov.pavel@gmail.com>
=> ec2: add private_ip_addresses to create_network_interface

boto/ec2/connection.py
**Changes**: 
_ec2.connection.modify_volume_attribute_
- Removed Description from known attributes
=> C2DEVEL-9659: remove description from modify_volume_attribute

boto/ec2/networkinterface.py, tests/unit/ec2/test_networkinterface.py
https://jira.croc.ru/browse/C2DEVEL-9726
=> C2DEVEL-9726: network interface spec - allow multiple interfaces along with eip assoc

boto/ec2/connection.py
https://jira.croc.ru/browse/C2DEVEL-9613
=> C2DEVEL-9613: ec2: rename virtualization types

boto/vpc/__init__.py
https://jira.croc.ru/browse/C2DEVEL-9916
=> C2DEVEL-9916: vpc: add tags param in create_customer_gateway and create_vpn_connection

boto/vpc/__init__.py
Changes:
* VPCConnection.create_vpc
Removed description parameter
=> VPC: Remove description from VPC

boto/ec2/connection.py
Add modify_volume method to support EC2 ModifyVolume
=> EC2: add modify_volume method

boto/ec2/image.py, boto/ec2/snapshot.py
*Changes:*
- Added attr `.is_shared` to snaps and images
=> EC2: add field is_shared to snaps and images

boto/ec2/connection.py
Changes:
- Added option for tagging on address allocation
=> EC2: enable tagging on address allocation

boto/ec2/connection.py
=> C2DEVEL-10629: Отключить функцию Suspend (приостановку) в API

boto/ec2/tariff.py
[C2DEVEL-12497](https://jira.croc.ru/browse/C2DEVEL-12497)
Changes
- Added OS field to tariff
- Added new instance type format
=> Add OS and new instance type Tariff format

boto/ec2/connection.py, boto/ec2/extnetwork.py
ExternalNetworks api now uses ec2-id or extnet_name + availability_zone
=> C2DEVEL-8028, C2DEVEL-9386, C2DEVEL-12245: Rework ExternalNetwork
